export { default as clock } from './clock.svg';
export { default as phone } from './phone.svg';
export { default as wheel } from './wheel.svg';
export { default as capacity } from './capacity.svg';
export { default as user } from './user.svg';
export { default as mail } from './mail.svg';
export { default as home } from './home.svg';
export { default as calendar } from './calendar.svg';
export { default as calender_dark } from './calender_dark.svg';
